plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

sourceCompatibility = targetCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

if (!hasProperty('mainClass')) {
    ext.mainClass = 'com.yumegod.obfuscator.Main'
}

repositories {
    mavenLocal()
    maven {
        name = "jitpack"
        url = 'https://jitpack.io'
    }
    mavenCentral()
}

dependencies {
    implementation project(':annotations')
//    implementation (project(':ByteCodeVirtualizer')) {
//        exclude group: 'org.ow2.asm'
//    }
    def asm_version = "9.8"

    implementation "org.ow2.asm:asm:$asm_version"
    implementation "org.ow2.asm:asm-tree:$asm_version"
    implementation "org.ow2.asm:asm-commons:$asm_version"
    implementation "org.ow2.asm:asm-analysis:$asm_version"
    implementation "org.ow2.asm:asm-util:$asm_version"

    implementation 'info.picocli:picocli:4.6.3'

    implementation 'org.slf4j:slf4j-api:1.7.25'
    implementation 'org.apache.logging.log4j:log4j-core:2.12.4'
    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.12.4'
    implementation 'org.apache.logging.log4j:log4j-api:2.12.4'

    implementation 'commons-io:commons-io:+'
    implementation 'org.apache.commons:commons-compress:1.26.1'

    implementation 'com.github.Carleslc.Simple-YAML:Simple-Yaml:1.8.4'
    implementation ('io.github.portlek:jsongration:2.0.11') {
        exclude group: 'org.simpleyaml'
    }
    implementation ('io.github.portlek:tomlgration:1.0.6') {
        exclude group: 'org.simpleyaml'
    }
}

shadowJar {
    archiveClassifier.set('')
}

assemble.dependsOn(shadowJar)

jar {
    manifest.attributes("Main-Class": getProperty('mainClass'))
}